### ISSUE TITLE
BLOG: The Hunger Game: the Fashion Influencer edition (Tuesday 15th November) & How to Make an Instagram Trendline (Monday 14th November)

### ISSUE THREAD

**Issue by juliepanda** [news-ai/news-ai.github.io#21]
##The Hunger Game: the Fashion Influencer edition

Everyone is an fashion influencer nowadays, but no two fashion influencers are created the same. Once you carefully curate a massive list of influencers whose style matches your brand's message, but working with a limited influencer budget, how do you know which influencer is generating content that is above-and-beyond the average?

I started out with the assumption that with an influencer with more followers should be getting more likes/comments on average, and you can generate a trend line based on a large enough sample size on what is the average number of likes/comments an influencer with X followers should be getting.

How I did it:
I generated a trend line with a fairly small sample of 47 fashion influencers of various follower count (20K - 750k) after collecting a day's (November 6th) worth of likes, comments, # of posts of all the influencers. After generating the graph, I sorted the influencers by those above the line and those below it.

The Y-Axis is the # of Likes/# of posts.
The X-Axis is the # of followers.

*If one influencer posts way more than another, then the total amount of likes would be skewed for the one that posts more, so I averaged daily # of likes with # of posts*

![screen shot 2016-11-06 at 10 43 37 pm](https://cloud.githubusercontent.com/assets/7796312/20046865/94cee486-a47c-11e6-9ead-2075de3ca2cd.png)
![screen shot 2016-11-06 at 10 51 19 pm](https://cloud.githubusercontent.com/assets/7796312/20046676/6c67b36c-a47a-11e6-99cd-07126cd0f2b7.png)

I also made one of comments to followers where:

The Y-Axis is the # of Comments/# of posts.
The X-Axis is the # of followers.

![screen shot 2016-11-06 at 10 51 35 pm](https://cloud.githubusercontent.com/assets/7796312/20046872/aa9cdd04-a47c-11e6-8dcf-b6d1c969ce45.png)
![screen shot 2016-11-06 at 10 51 48 pm](https://cloud.githubusercontent.com/assets/7796312/20046677/6c67abe2-a47a-11e6-9da2-93222cd2bbd8.png)

You can easily generate this graph with your own media lists, too!

I've made this graph with the Trendline generating tool in the NewsAI Tabulae platform, a CRM for PR that keep your media lists in sync with one another and help you keep up to date with the content generated by your contacts.

There's a free 7-days trial (no credit card collected) and you can try recreating this graph with your own media lists of fashion influencer handles (Tabulae will fetch the likes/posts/comments counts for you!). 

While this is only a snapshot of one day, I am curious to see what sort of pattern will arise with data collected over a couple months, but that's another blogpost for another day.

May the odds be ever in your favor.

Holla your comments @julie_panda on Twitter.

**Comment by juliepanda** [comment]
alternate titles:
The Hunger Game: the Fashion Influencer edition (Introducing Trendline tool)
Dead simple way to find out which influencer has the best following
Narrow down your massive influencer list with this one trick
Maximizing your limited influencer budget

**Comment by juliepanda** [comment]
COMPANION PIECE LOL idk why its numbered weirdly

## Tutorial: How to Make an Instagram Trendline
1. Import an Existing Sheet with Instagram handles

_If there's a name, we'll fetch it_

![how_to_instagram_trendline_pg1](https://cloud.githubusercontent.com/assets/7796312/20083977/91d99134-a52d-11e6-9e0e-1dc243ffdd30.png)
1. Click on "Show/Hide Columns" icon button on the top bar and activate some of the Instagram metrics columns you'd like to use (e.g. Instagram followers, comments, etc)

![how_to_instagram_trendline_pg2](https://cloud.githubusercontent.com/assets/7796312/20083981/992ac994-a52d-11e6-9ff6-b103755235f1.png)

![how_to_instagram_trendline_pg3](https://cloud.githubusercontent.com/assets/7796312/20083999/ab2b154a-a52d-11e6-932c-7b232709456c.png)
1. Select the contacts you'd like to generate the graph from (if you click on Selected column head, it will select all of the contacts)
2. In the top right, there's a dropdown icon button called "Analyze" and click on "Instagram Trendline".

![how_to_instagram_trendline_pg4](https://cloud.githubusercontent.com/assets/7796312/20084009/b32aba48-a52d-11e6-8c6e-b1b52a4bbe7e.png)
1. Voila!
   ![how_to_instagram_trendline_pg5](https://cloud.githubusercontent.com/assets/7796312/20084012/b95082ae-a52d-11e6-92ee-a98cc306e260.png)

**Comment by AbhiAgarwal** [comment]
@ycp217 can you have a simple definition of what a "Trendline" means?

**Comment by juliepanda** [comment]
A trendline attempts to show a relationship between two attributes from selected contacts that could support some ideas about the selected contacts. E.g. "more followers, more likes per post".
