### ISSUE TITLE
BLOG: Client directory

### ISSUE THREAD

**Issue by juliepanda** [news-ai/news-ai.github.io#28]
You can assign a Client name attribute to a List so you can easily find it in the Client Directory.

1. Assign a Client name by click on "Add Tag & Client"
![tutorial_client_directory_2](https://cloud.githubusercontent.com/assets/7796312/20206126/5563606e-a7ac-11e6-8ae1-14baf41dadd4.png)

2. Find them under "Client Directory"
![tutorial_client_directory_1](https://cloud.githubusercontent.com/assets/7796312/20206125/55630be6-a7ac-11e6-9dc4-486946d944f6.png)

Voila!

**Comment by AbhiAgarwal** [comment]
@ycp217 can you retake pic 1 here? I don't think it'll be a good idea to expose emails in images

**Comment by juliepanda** [comment]
![client_1](https://cloud.githubusercontent.com/assets/7796312/20243584/a51a3f98-a92c-11e6-9191-b94e594c52e5.png)
